### ISSUE TITLE
Characters 親,新....

### ISSUE THREAD

**Issue by ghost** [GuiWonder/MoonStarsKai#1]

**Comment by ghost** [comment]
The first stroke of "亲" (part of "親", "新"...) should be horizontal, not vertical

I.Ming (新 榇 薪 親 儭 嚫 櫬 襯)
![IMG_20230601_185531](https://github.com/GuiWonder/MoonStarsKai/assets/100918126/86289cae-90e6-4abc-a204-af0507fe73dc)
Bright Moon Kai 
![IMG_20230601_184853](https://github.com/GuiWonder/MoonStarsKai/assets/100918126/41894160-d470-4d20-83b1-5d5035d1e2bd)

**Comment by GuiWonder** [comment]
您好，本字體並未按照[一點字坊「傳承字形標準化文件」](https://github.com/ichitenfont/inheritedglyphs)製作。本字體基於[霞鶩文楷 TC](https://github.com/lxgw/LxgwWenkaiTC)，[霞鶩文楷 TC](https://github.com/lxgw/LxgwWenkaiTC) 是一款非常優秀的[「傳承字形標準化文件」](https://github.com/ichitenfont/inheritedglyphs)字體。如果本字體同樣按[「傳承字形標準化文件」](https://github.com/ichitenfont/inheritedglyphs)方向製作，必然會失去它存在的價値，希望您能夠理解。

本字體主要參考了刻本《洪武正韻》。「亲」在刻本中橫點與豎點並未統一，以豎點居多，因此便使用了豎點。
![picture](https://github.com/GuiWonder/MoonStarsKai/assets/55447192/222d338e-a17f-41d2-aa92-84dc168a388d)
